USE MaritimeLogisticsDB; GO 

SELECT name AS Tabla, create_date AS FechaCreacion FROM sys.tables ORDER BY name;

INSERT INTO HARBOR (name, region, city, country, port_type) VALUES
('Port of Buenos Aires', 'AMBA', 'Buenos Aires', 'Argentina', 'DAY'),
('Port of Valparaiso', 'Valparaiso Region', 'Valparaiso', 'Chile', 'NIGHT'),
('Port of Miami', 'Florida', 'Miami', 'United States', 'DAY'),
('Port of Rotterdam', 'South Holland', 'Rotterdam', 'Netherlands', 'NIGHT'),
('Port of Barcelona', 'Catalonia', 'Barcelona', 'Spain', 'DAY'),
('Port of Yokohama', 'Kanagawa', 'Yokohama', 'Japan', 'NIGHT'),
('Port of Hamburg', 'Hamburg', 'Hamburg', 'Germany', 'DAY'),
('Port of Santos', 'São Paulo', 'Santos', 'Brazil', 'NIGHT'),
('Port of Vancouver', 'British Columbia', 'Vancouver', 'Canada', 'DAY'),
('Port of Cape Town', 'Western Cape', 'Cape Town', 'South Africa', 'NIGHT'),
('Port of Melbourne', 'Victoria', 'Melbourne', 'Australia', 'DAY'),
('Port of Singapore', 'Singapore', 'Singapore', 'Singapore', 'NIGHT'),
('Port of Naples', 'Campania', 'Naples', 'Italy', 'DAY'),
('Port of Marseille', 'Provence', 'Marseille', 'France', 'NIGHT'),
('Port of Doha', 'Doha', 'Doha', 'Qatar', 'DAY'),
('Port of Dubai', 'Dubai', 'Dubai', 'United Arab Emirates', 'NIGHT'),
('Port of Mumbai', 'Maharashtra', 'Mumbai', 'India', 'DAY'),
('Port of Dublin', 'Leinster', 'Dublin', 'Ireland', 'NIGHT'),
('Port of Helsinki', 'Uusimaa', 'Helsinki', 'Finland', 'DAY'),
('Port of Casablanca', 'Casablanca-Settat', 'Casablanca', 'Morocco', 'NIGHT'),
('Port of New York', 'New York State', 'New York', 'United States', 'DAY'),
('Port of Los Angeles', 'California', 'Los Angeles', 'United States', 'NIGHT'),
('Port of Antwerp', 'Flanders', 'Antwerp', 'Belgium', 'DAY'),
('Port of Genoa', 'Liguria', 'Genoa', 'Italy', 'NIGHT'),
('Port of Le Havre', 'Normandy', 'Le Havre', 'France', 'DAY'),
('Port of Manila', 'Metro Manila', 'Manila', 'Philippines', 'NIGHT'),
('Port of Busan', 'South Gyeongsang', 'Busan', 'South Korea', 'DAY'),
('Port of Shanghai', 'Shanghai Municipality', 'Shanghai', 'China', 'NIGHT'),
('Port of Hong Kong', 'Hong Kong', 'Hong Kong', 'China', 'DAY'),
('Port of Antwerp-Bruges', 'Flanders', 'Zeebrugge', 'Belgium', 'NIGHT'),
('Port of San Juan', 'Puerto Rico', 'San Juan', 'United States', 'DAY'),
('Port of Guayaquil', 'Guayas', 'Guayaquil', 'Ecuador', 'NIGHT'),
('Port of Callao', 'Lima Region', 'Callao', 'Peru', 'DAY'),
('Port of Montevideo', 'Montevideo Department', 'Montevideo', 'Uruguay', 'NIGHT'),
('Port of Tallinn', 'Harju County', 'Tallinn', 'Estonia', 'DAY'),
('Port of Riga', 'Riga Region', 'Riga', 'Latvia', 'NIGHT'),
('Port of Oslo', 'Oslo County', 'Oslo', 'Norway', 'DAY'),
('Port of Gothenburg', 'Västra Götaland', 'Gothenburg', 'Sweden', 'NIGHT'),
('Port of Alexandria', 'Alexandria Governorate', 'Alexandria', 'Egypt', 'DAY'),
('Port of Izmir', 'Izmir Province', 'Izmir', 'Turkey', 'NIGHT');

SELECT * FROM HARBOR;