USE MaritimeSystemDB; GO

SELECT name AS Tabla, create_date AS FechaCreacion
FROM sys.tables ORDER BY name;

IF OBJECT_ID('dbo.SHIPBOARD_STAFFING') IS NOT NULL
BEGIN
    TRUNCATE TABLE SHIPBOARD_STAFFING;
    PRINT 'La tabla SHIPBOARD_STAFFING fue vaciada correctamente.';
END
ELSE
BEGIN
    PRINT 'La tabla SHIPBOARD_STAFFING >>> NO existe.';
END

SELECT * FROM SHIPBOARD_STAFFING;